# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 14:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map_Info',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=600)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_by', models.CharField(max_length=200)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('created_time', models.TimeField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
