# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-25 10:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('con_string', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
