# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-26 18:33
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnections',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 11, 26, 23, 33, 30, 50907)),
        ),
        migrations.AddField(
            model_name='databaseconnections',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='databaseconnections',
            name='integrated_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
