# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-06 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_auto_20181126_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnections',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
