# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 06:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('layer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('layer_name', models.CharField(max_length=200, null=True)),
                ('table_name', models.CharField(max_length=200)),
                ('layer_type', models.CharField(max_length=100, null=True)),
                ('geom_type', models.CharField(max_length=30, null=True)),
                ('srid', models.IntegerField()),
                ('extent', models.TextField()),
                ('orig_extent', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(max_length=200)),
                ('upload_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('lyr_model_name', models.CharField(blank=True, max_length=200)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('icon', models.CharField(max_length=500, null=True)),
                ('style', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_name', models.CharField(max_length=300)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('U', 'User'), ('D', 'Department')], max_length=50)),
                ('permission_type', models.CharField(choices=[('V', 'View'), ('D', 'Download')], max_length=25)),
                ('Info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Info')),
            ],
        ),
    ]
