# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 18:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('srid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('proj4', models.CharField(max_length=300)),
                ('srs', models.TextField()),
                ('extent', django.contrib.gis.db.models.fields.PolygonField(srid=0)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_per_unit', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
