# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_raster_info_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='main_category',
            field=models.CharField(default='Unspecified', max_length=500, null=True),
        ),
    ]
