# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_auto_20180325_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='Info_id',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
