# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_auto_20180325_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='layer_id',
            new_name='id',
        ),
    ]
