# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0007_auto_20180325_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='app_label',
            field=models.CharField(default='layers', max_length=100, null=True),
        ),
    ]
