# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0009_info_orig_srid'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='rst_overview_list',
            field=models.CharField(default='2,4,8', max_length=100, null=True),
        ),
    ]
