# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0010_info_rst_overview_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='extent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='geom_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
