# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-15 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0012_auto_20180517_1005'),
        ('layers', '0012_auto_20180508_1025'),
    ]

    operations = [
    ]
