# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-03 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0014_auto_20180815_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='lyr_model_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
