# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0015_auto_20180903_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='orig_srid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
