# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-01 12:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_auto_20181206_1907'),
        ('layers', '0016_auto_20180904_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='layer_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='label',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='lyr_col_name',
            field=models.CharField(default='geom', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='remote_conn_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.DatabaseConnections'),
        ),
        migrations.AlterField(
            model_name='info',
            name='main_category',
            field=models.ForeignKey(db_column='main_category', default='Unspecified', max_length=500, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='layers.layer_categories', to_field='category'),
        ),
        migrations.AlterField(
            model_name='info',
            name='orig_extent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='rst_overview_list',
            field=models.CharField(blank=True, default='2,4,8', max_length=100, null=True),
        ),
    ]
