# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryTemplate',
            fields=[
                ('dir_id', models.AutoField(primary_key=True, serialize=False)),
                ('dir_name', models.CharField(max_length=255)),
                ('dir_level', models.IntegerField()),
                ('act_addby', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dir_path', models.CharField(blank=True, max_length=255, null=True)),
                ('lft', models.IntegerField(blank=True, null=True)),
                ('rght', models.IntegerField(blank=True, null=True)),
                ('tree_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Directory Template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('dir_id', models.AutoField(primary_key=True, serialize=False)),
                ('dir_name', models.CharField(max_length=255)),
                ('dir_level', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('project_id', models.CharField(max_length=100)),
                ('dir_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_title', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('lft', models.IntegerField(blank=True, null=True)),
                ('rght', models.IntegerField(blank=True, null=True)),
                ('tree_id', models.IntegerField(blank=True, null=True)),
                ('parent_dir_id', mptt.fields.TreeForeignKey(blank=True, db_column='parent_dir_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.Directory')),
            ],
            options={
                'verbose_name': 'Directories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.PositiveIntegerField()),
                ('file_name', models.CharField(max_length=300)),
                ('file_title', models.CharField(max_length=300)),
                ('dir_id', models.ForeignKey(db_column='dir_id', on_delete=django.db.models.deletion.CASCADE, to='projects.Directory')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Files',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name_short', models.CharField(max_length=255)),
                ('project_type', models.CharField(blank=True, choices=[('local', 'Local'), ('foreign', 'Foreign')], max_length=50, null=True)),
                ('project_addby', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['project_name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='files',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together=set([('dir_id', 'project_id')]),
        ),
    ]
