# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 07:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('fileupload', 'File Upload Rights'),),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activity_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=100, null=True)),
                ('app_label', models.CharField(max_length=100)),
                ('view_name', models.CharField(max_length=100)),
                ('view_des', models.CharField(blank=True, max_length=600, null=True)),
                ('error_des', models.CharField(blank=True, max_length=600, null=True)),
                ('access_date', models.DateField(blank=True, null=True)),
                ('access_time', models.TimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('params_get', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('params_post', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
