# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-02 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ferrp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('upload_date', models.DateField()),
                ('upload_time', models.TimeField()),
                ('icon', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items_Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=300)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('U', 'User'), ('D', 'Department')], max_length=50)),
                ('permission_type', models.CharField(choices=[('O', 'Owner'), ('V', 'View'), ('D', 'Download'), ('S', 'Save')], max_length=25)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
