# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferrp', '0003_auto_20180404_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc_Info',
        ),
    ]
