# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferrp', '0004_delete_doc_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_permission',
            name='permission_type',
            field=models.CharField(choices=[('P', 'Public'), ('O', 'Owner'), ('V', 'View'), ('D', 'Download'), ('S', 'Save')], max_length=25),
        ),
    ]
