# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-15 20:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RsFlood10Gsd100',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
                ('extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=900913)),
            ],
            options={
                'db_table': 'rs_flood_10_gsd_100',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RsFlood14Gsd100',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
                ('extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=900913)),
            ],
            options={
                'db_table': 'rs_flood_14_gsd_100',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RsFuelsGsd100',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
                ('extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=900913)),
            ],
            options={
                'db_table': 'rs_fuels_gsd_100',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RsGlcfGsd100',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
                ('extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=900913)),
            ],
            options={
                'db_table': 'rs_glcf_gsd_100',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RsHospitalGsd100',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
                ('extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=900913)),
            ],
            options={
                'db_table': 'rs_hospital_gsd_100',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RsPopulationGsd100',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
                ('extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=900913)),
            ],
            options={
                'db_table': 'rs_population_gsd_100',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RsSchoolsGsd100',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
                ('extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=900913)),
            ],
            options={
                'db_table': 'rs_schools_gsd_100',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDistrict',
            fields=[
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('name_admin', models.CharField(blank=True, max_length=50, null=True)),
                ('name_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.SmallIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'tbl_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTehsil',
            fields=[
                ('name_admin', models.CharField(blank=True, max_length=50, null=True)),
                ('name_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('division_id', models.SmallIntegerField(blank=True, null=True)),
                ('parent_id', models.SmallIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'tbl_tehsil',
                'managed': False,
            },
        ),
    ]
