# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-15 20:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSelectionSelectedsites',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(blank=True, max_length=256, null=True)),
                ('project_id', models.CharField(blank=True, max_length=256, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857)),
            ],
            options={
                'db_table': 'site_selection_selectedsites',
                'managed': False,
            },
        ),
    ]
