# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-15 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_selection', '0003_auto_20181116_0130'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='siteselectionselectedsites',
            table='site_selection_selectedsites',
        ),
    ]
