# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMap',
            fields=[
                ('activity_map_id', models.IntegerField(primary_key=True, serialize=False)),
                ('survey_type_id', models.IntegerField(blank=True, null=True)),
                ('property_id', models.IntegerField(blank=True, null=True)),
                ('property_type_id', models.IntegerField(blank=True, null=True)),
                ('show', models.IntegerField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('group_number', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'activity_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('age_group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age_group_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'age_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('app_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=12, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_locked', models.IntegerField(blank=True, null=True)),
                ('is_expired', models.IntegerField(blank=True, null=True)),
                ('password_expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoundaryWall',
            fields=[
                ('boundary_wall_id', models.IntegerField(primary_key=True, serialize=False)),
                ('boundary_wall_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'boundary_wall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BridgeType',
            fields=[
                ('bridge_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bridge_type_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'bridge_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingInformation',
            fields=[
                ('building_information_id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_information_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'building_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingOwnership',
            fields=[
                ('building_ownership_id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_ownership_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'building_ownership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingSituated',
            fields=[
                ('building_situated_id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_situated_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'building_situated',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('building_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_type_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'building_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectedInfrastructure',
            fields=[
                ('connected_infrastructure_id', models.IntegerField(primary_key=True, serialize=False)),
                ('connected_infrastructure_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'connected_infrastructure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DamageLevel',
            fields=[
                ('damage_level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('damage_level_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'damage_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisasterDamage',
            fields=[
                ('disaster_damage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disaster_damage_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'disaster_damage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(blank=True, max_length=500, null=True)),
                ('estimated_population', models.IntegerField(blank=True, null=True)),
                ('estimated_surveys', models.IntegerField(blank=True, null=True)),
                ('surveyors', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('surveyed', models.NullBooleanField()),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictGroupsPercentageTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('district_name', models.CharField(blank=True, max_length=500, null=True)),
                ('property_type_id', models.IntegerField(blank=True, null=True)),
                ('group_name', models.TextField(blank=True, null=True)),
                ('group_option', models.TextField(blank=True, null=True)),
                ('male', models.BigIntegerField(blank=True, null=True)),
                ('male_pecentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('female', models.BigIntegerField(blank=True, null=True)),
                ('female_pecentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transgender', models.BigIntegerField(blank=True, null=True)),
                ('trans_pecentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'district_groups_percentage_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
                ('district_name', models.CharField(blank=True, max_length=500, null=True)),
                ('tehsil_name', models.CharField(blank=True, max_length=500, null=True)),
                ('qanungoi_halqa_name', models.CharField(blank=True, max_length=500, null=True)),
                ('patwar_circle_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mauza_name', models.CharField(blank=True, max_length=500, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'district_hierarchy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictStatsTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('district_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mauzas', models.BigIntegerField(blank=True, null=True)),
                ('patwar_circles', models.BigIntegerField(blank=True, null=True)),
                ('qanungoi_halqas', models.BigIntegerField(blank=True, null=True)),
                ('tehsils', models.BigIntegerField(blank=True, null=True)),
                ('educational_institutes', models.BigIntegerField(blank=True, null=True)),
                ('health_facilities', models.BigIntegerField(blank=True, null=True)),
                ('total_surveys', models.BigIntegerField(blank=True, null=True)),
                ('male', models.BigIntegerField(blank=True, null=True)),
                ('female', models.BigIntegerField(blank=True, null=True)),
                ('transgender', models.BigIntegerField(blank=True, null=True)),
                ('estimated_population', models.IntegerField(blank=True, null=True)),
                ('estimated_surveys', models.IntegerField(blank=True, null=True)),
                ('surveyors', models.IntegerField(blank=True, null=True)),
                ('checked_surveys', models.BigIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('psds', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'district_stats_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictStatsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('district_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mauzas', models.BigIntegerField(blank=True, null=True)),
                ('patwar_circles', models.BigIntegerField(blank=True, null=True)),
                ('qanungoi_halqas', models.BigIntegerField(blank=True, null=True)),
                ('tehsils', models.BigIntegerField(blank=True, null=True)),
                ('educational_institutes', models.BigIntegerField(blank=True, null=True)),
                ('health_facilities', models.BigIntegerField(blank=True, null=True)),
                ('total_surveys', models.BigIntegerField(blank=True, null=True)),
                ('male', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('female', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('transgender', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('estimated_population', models.IntegerField(blank=True, null=True)),
                ('estimated_surveys', models.IntegerField(blank=True, null=True)),
                ('surveyors', models.IntegerField(blank=True, null=True)),
                ('checked_surveys', models.BigIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('psds', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'district_stats_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictTemp',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(blank=True, max_length=500, null=True)),
                ('estimated_population', models.IntegerField(blank=True, null=True)),
                ('estimated_surveys', models.IntegerField(blank=True, null=True)),
                ('surveyors', models.IntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'district_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EduBuildingStatsTab',
            fields=[
                ('edu_building_stats_tab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('survey_id', models.IntegerField(blank=True, null=True)),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
                ('type_of_construction', models.CharField(blank=True, max_length=500, null=True)),
                ('institute_level', models.CharField(blank=True, max_length=500, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('survey_type_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edu_building_stats_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('education_level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('education_level_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'education_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyTrainingDepartment',
            fields=[
                ('emergency_training_department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emergency_training_department_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'emergency_training_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyTrainingType',
            fields=[
                ('emergency_training_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emergency_training_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'emergency_training_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EpidemicDisease',
            fields=[
                ('epidemic_disease_id', models.IntegerField(primary_key=True, serialize=False)),
                ('epidemic_disease_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'epidemic_disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyCast',
            fields=[
                ('family_cast_id', models.IntegerField(primary_key=True, serialize=False)),
                ('family_cast_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'family_cast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialCalcDetail',
            fields=[
                ('financial_calc_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
                ('financial_calc_parameter_id', models.IntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'financial_calc_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialCalcParameter',
            fields=[
                ('financial_calc_parameter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parameter_type', models.CharField(blank=True, max_length=500, null=True)),
                ('survey_type_id', models.IntegerField(blank=True, null=True)),
                ('parameter_name', models.CharField(blank=True, max_length=500, null=True)),
                ('param_property_id', models.IntegerField(blank=True, null=True)),
                ('sub_parameter_name', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_param_property_id', models.IntegerField(blank=True, null=True)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aggregation', models.CharField(blank=True, max_length=500, null=True)),
                ('value_field', models.CharField(blank=True, max_length=500, null=True)),
                ('condition_type', models.IntegerField(blank=True, null=True)),
                ('parameter_heading_id', models.IntegerField(blank=True, null=True)),
                ('parameter_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financial_calc_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GovtCompensation',
            fields=[
                ('govt_compensation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('govt_compensation_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'govt_compensation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthFacilityType',
            fields=[
                ('health_facility_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('health_facility_type_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'health_facility_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthInformation',
            fields=[
                ('health_information_id', models.IntegerField(primary_key=True, serialize=False)),
                ('health_information_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'health_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HohLandAquired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.IntegerField()),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
                ('agricultural_land', models.IntegerField(blank=True, null=True)),
                ('agricultural_land_unit', models.CharField(blank=True, max_length=500, null=True)),
                ('agricultural_land_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cultivated_land_owner', models.IntegerField(blank=True, null=True)),
                ('cultivated_land_owner_unit', models.CharField(blank=True, max_length=500, null=True)),
                ('cultivated_land_owner_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cultivated_land_tenant', models.IntegerField(blank=True, null=True)),
                ('cultivated_land_tenant_unit', models.CharField(blank=True, max_length=500, null=True)),
                ('cultivated_land_tenant_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'hoh_land_aquired',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandOwnership',
            fields=[
                ('land_ownership_id', models.IntegerField(primary_key=True, serialize=False)),
                ('land_ownership_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'land_ownership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandUnit',
            fields=[
                ('land_unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('land_unit_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'land_unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LayyahFloodData1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.IntegerField(blank=True, null=True)),
                ('survey_type_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('survey_datetime', models.DateTimeField(blank=True, null=True)),
                ('surveyor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('district_name', models.CharField(blank=True, max_length=500, null=True)),
                ('tehsil_name', models.CharField(blank=True, max_length=500, null=True)),
                ('qanungoi_halqa_name', models.CharField(blank=True, max_length=500, null=True)),
                ('patwar_circle_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mauza_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=500, null=True)),
                ('family_cast', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('hoh_name', models.CharField(blank=True, max_length=500, null=True)),
                ('cnic', models.CharField(blank=True, max_length=500, null=True)),
                ('kacha_rooms', models.IntegerField(blank=True, null=True)),
                ('pakka_rooms', models.IntegerField(blank=True, null=True)),
                ('last_disaster_year', models.IntegerField(blank=True, null=True)),
                ('was_house_damaged', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'layyah_flood_data_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LayyahFloodData2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.IntegerField(blank=True, null=True)),
                ('age_group_male_30_to_45_years', models.BigIntegerField(blank=True, db_column='age_group_male_30+ to 45 Years', null=True)),
                ('age_group_male_5_to_14_years', models.BigIntegerField(blank=True, db_column='age_group_male_5+ to 14 Years', null=True)),
                ('age_group_male_up_to_3_years', models.BigIntegerField(blank=True, db_column='age_group_male_Up to 3 Years', null=True)),
                ('age_group_male_45_to_60_years', models.BigIntegerField(blank=True, db_column='age_group_male_45+ to 60 Years', null=True)),
                ('age_group_male_above_60_years', models.BigIntegerField(blank=True, db_column='age_group_male_Above 60 Years', null=True)),
                ('age_group_male_18_to_30_years', models.BigIntegerField(blank=True, db_column='age_group_male_18+ to 30 Years', null=True)),
                ('age_group_male_14_to_18_years', models.BigIntegerField(blank=True, db_column='age_group_male_14+ to 18 Years', null=True)),
                ('age_group_male_3_to_5_years', models.BigIntegerField(blank=True, db_column='age_group_male_3+ to 5 Years', null=True)),
                ('age_group_female_up_to_3_years', models.BigIntegerField(blank=True, db_column='age_group_female_Up to 3 Years', null=True)),
                ('age_group_female_45_to_60_years', models.BigIntegerField(blank=True, db_column='age_group_female_45+ to 60 Years', null=True)),
                ('age_group_female_3_to_5_years', models.BigIntegerField(blank=True, db_column='age_group_female_3+ to 5 Years', null=True)),
                ('age_group_female_14_to_18_years', models.BigIntegerField(blank=True, db_column='age_group_female_14+ to 18 Years', null=True)),
                ('age_group_female_5_to_14_years', models.BigIntegerField(blank=True, db_column='age_group_female_5+ to 14 Years', null=True)),
                ('age_group_female_18_to_30_years', models.BigIntegerField(blank=True, db_column='age_group_female_18+ to 30 Years', null=True)),
                ('age_group_female_30_to_45_years', models.BigIntegerField(blank=True, db_column='age_group_female_30+ to 45 Years', null=True)),
                ('age_group_female_above_60_years', models.BigIntegerField(blank=True, db_column='age_group_female_Above 60 Years', null=True)),
                ('male_diable', models.BigIntegerField(blank=True, null=True)),
                ('female_disable', models.BigIntegerField(blank=True, null=True)),
                ('sheep', models.BigIntegerField(blank=True, db_column='Sheep', null=True)),
                ('goat', models.BigIntegerField(blank=True, db_column='Goat', null=True)),
                ('buffalo', models.BigIntegerField(blank=True, db_column='Buffalo', null=True)),
                ('cow', models.BigIntegerField(blank=True, db_column='Cow', null=True)),
                ('donkeys', models.BigIntegerField(blank=True, db_column='Donkeys', null=True)),
                ('horses', models.BigIntegerField(blank=True, db_column='Horses', null=True)),
                ('camels', models.BigIntegerField(blank=True, db_column='Camels', null=True)),
                ('hens', models.BigIntegerField(blank=True, db_column='Hens', null=True)),
            ],
            options={
                'db_table': 'layyah_flood_data_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LevelOfHelpfulness',
            fields=[
                ('level_of_helpfulness_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level_of_helpfulness_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'level_of_helpfulness',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('livestock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('livestock_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'livestock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LivingFacility',
            fields=[
                ('living_facility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('living_facility_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'living_facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('location_datetime', models.DateTimeField(blank=True, null=True)),
                ('upload_datetime', models.DateTimeField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationDel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location_del',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MagnitudeOfLoss',
            fields=[
                ('magnitude_of_loss_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mangnitude_of_loss_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'magnitude_of_loss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mauza',
            fields=[
                ('mauza_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mauza_name', models.CharField(blank=True, max_length=500, null=True)),
                ('hadbast_no', models.CharField(blank=True, max_length=500, null=True)),
                ('patwar_circle_id', models.IntegerField(blank=True, null=True)),
                ('mauza_status', models.NullBooleanField()),
                ('union_council_id', models.IntegerField(blank=True, null=True)),
                ('surveyed', models.NullBooleanField()),
                ('geom', models.TextField(blank=True, null=True)),
                ('geom1', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mauza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MauzaFim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
                ('mauza_name', models.CharField(blank=True, max_length=500, null=True)),
                ('hadbast_no', models.CharField(blank=True, max_length=500, null=True)),
                ('patwar_circle_id', models.IntegerField(blank=True, null=True)),
                ('mauza_status', models.NullBooleanField()),
                ('union_council_id', models.IntegerField(blank=True, null=True)),
                ('surveyed', models.NullBooleanField()),
                ('geom', models.TextField(blank=True, null=True)),
                ('geom1', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mauza_fim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MauzaLandAquired',
            fields=[
                ('mauza_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mauza_agricultural_land_acre', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('mauza_cultivated_land_owner_acre', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('mauza_cultivated_land_tenant_acre', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'mauza_land_aquired',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('medical_facility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medical_facility_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'medical_facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeOfInformation',
            fields=[
                ('mode_of_information_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mode_of_information_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'mode_of_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyIncome',
            fields=[
                ('monthly_income_id', models.IntegerField(primary_key=True, serialize=False)),
                ('monthly_income_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'monthly_income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MouzaPhase1',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('hb_no', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('drought', models.CharField(blank=True, max_length=10, null=True)),
                ('f_district', models.CharField(blank=True, max_length=254, null=True)),
                ('f_tehsil', models.CharField(blank=True, max_length=254, null=True)),
                ('qh', models.CharField(blank=True, max_length=254, null=True)),
                ('f_pc', models.CharField(blank=True, max_length=254, null=True)),
                ('mouza_name', models.CharField(blank=True, max_length=254, null=True)),
                ('total_popl', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('flood_zone', models.IntegerField(blank=True, null=True)),
                ('f_drought', models.CharField(blank=True, max_length=254, null=True)),
                ('created_us', models.CharField(blank=True, max_length=254, null=True)),
                ('created_da', models.DateField(blank=True, null=True)),
                ('last_edite', models.CharField(blank=True, max_length=254, null=True)),
                ('last_edi_1', models.DateField(blank=True, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_len', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('mauza_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mouza_phase1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaturalDisaster',
            fields=[
                ('natural_disaster_id', models.IntegerField(primary_key=True, serialize=False)),
                ('natural_disaster_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'natural_disaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NgoTypeOfWork',
            fields=[
                ('ngo_type_of_work_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ngo_type_of_work_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ngo_type_of_work',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.IntegerField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterHeading',
            fields=[
                ('parameter_heading_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parameter_heading_name', models.CharField(blank=True, max_length=500, null=True)),
                ('unit', models.CharField(blank=True, max_length=500, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'parameter_heading',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterTemp',
            fields=[
                ('parameter_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'parameter_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatwarCircle',
            fields=[
                ('patwar_circle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patwar_circle_name', models.CharField(blank=True, max_length=500, null=True)),
                ('qanungoi_halqa_id', models.IntegerField(blank=True, null=True)),
                ('surveyed', models.NullBooleanField()),
            ],
            options={
                'db_table': 'patwar_circle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('personality_id', models.IntegerField(primary_key=True, serialize=False)),
                ('personality_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'personality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(blank=True, max_length=500, null=True)),
                ('property_type_id', models.IntegerField(blank=True, null=True)),
                ('value_lower_limit', models.CharField(blank=True, max_length=500, null=True)),
                ('value_upper_limit', models.CharField(blank=True, max_length=500, null=True)),
                ('property_value_type', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('property_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('property_type_name', models.CharField(blank=True, max_length=500, null=True)),
                ('ui', models.CharField(blank=True, max_length=500, null=True)),
                ('genders', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'property_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QanungoiHalqa',
            fields=[
                ('qanungoi_halqa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('qanungoi_halqa_name', models.CharField(blank=True, max_length=500, null=True)),
                ('tehsil_id', models.IntegerField(blank=True, null=True)),
                ('surveyed', models.NullBooleanField()),
            ],
            options={
                'db_table': 'qanungoi_halqa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('religion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('religion_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'religion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResidenceInformation',
            fields=[
                ('residence_information_id', models.IntegerField(primary_key=True, serialize=False)),
                ('residence_information_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'residence_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespondentRelation',
            fields=[
                ('respondent_relation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('respondent_relation_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'respondent_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='River10KmBuffer',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('layer', models.CharField(blank=True, max_length=17, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('buff_dist', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('orig_fid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'river_10km_buffer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='River5KmProjected',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('layer', models.CharField(blank=True, max_length=17, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('buff_dist', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('orig_fid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'river_5km_projected',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiversProjected',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('objectid_1', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('layer', models.CharField(blank=True, max_length=17, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('created_us', models.CharField(blank=True, max_length=254, null=True)),
                ('created_da', models.DateField(blank=True, null=True)),
                ('last_edite', models.CharField(blank=True, max_length=254, null=True)),
                ('last_edi_1', models.DateField(blank=True, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_len', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rivers_projected',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoadCategory',
            fields=[
                ('road_category_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('road_category_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'road_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoadMaintenanceAuthority',
            fields=[
                ('road_maintenance_authority_id', models.IntegerField(primary_key=True, serialize=False)),
                ('road_maintenance_authority', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'road_maintenance_authority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('role_permission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('user_permission_id', models.IntegerField(blank=True, null=True)),
                ('update_permission', models.IntegerField(blank=True, null=True)),
                ('create_permission', models.IntegerField(blank=True, null=True)),
                ('delete_permission', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SewerageSystem',
            fields=[
                ('sewerage_system_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sewerage_system_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sewerage_system',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceOfIncome',
            fields=[
                ('source_of_income_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_of_income_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'source_of_income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('survey_type_id', models.IntegerField(blank=True, null=True)),
                ('surveyor_id', models.IntegerField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('survey_datetime', models.DateTimeField(blank=True, null=True)),
                ('imei_no', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_datetime', models.DateTimeField(blank=True, null=True)),
                ('verified', models.NullBooleanField()),
            ],
            options={
                'db_table': 'survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyProperty',
            fields=[
                ('survey_property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('survey_id', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('property_id', models.IntegerField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survey_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyType',
            fields=[
                ('survey_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('survey_type_name', models.CharField(blank=True, max_length=500, null=True)),
                ('survey_table_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'survey_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('tehsil_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tehsil_name', models.CharField(blank=True, max_length=500, null=True)),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('surveyed', models.NullBooleanField()),
            ],
            options={
                'db_table': 'tehsil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalAgriculturalLandUnit',
            fields=[
                ('total_agricultural_land_unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_agricultural_land_unit_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'total_agricultural_land_unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('transport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transport_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'transport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfBusiness',
            fields=[
                ('type_of_business_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_business_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfChemical',
            fields=[
                ('type_of_chemical_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_chemical_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_chemical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfConstruction',
            fields=[
                ('type_of_construction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_construction_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_construction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfCrop',
            fields=[
                ('type_of_crop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_crop_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_crop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfDisability',
            fields=[
                ('type_of_disability_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_disability_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_disability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfFamily',
            fields=[
                ('type_of_family_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_family_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfGraveyard',
            fields=[
                ('type_of_graveyard_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_graveyard_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_graveyard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfIndustry',
            fields=[
                ('type_of_industry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_industry_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_industry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfInstitute',
            fields=[
                ('type_of_institute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_institute_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_institute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfPark',
            fields=[
                ('type_of_park_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_park_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_park',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfRelief',
            fields=[
                ('type_of_relief_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_relief_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_relief',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfReligiousBuilding',
            fields=[
                ('type_of_religious_building_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_religious_building_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'type_of_religious_building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnionCouncil',
            fields=[
                ('union_council_id', models.IntegerField(primary_key=True, serialize=False)),
                ('union_council_name', models.CharField(blank=True, max_length=500, null=True)),
                ('union_council_no', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'union_council',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user_permission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_permission_name', models.CharField(blank=True, max_length=50, null=True)),
                ('target_page_url', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterSupply',
            fields=[
                ('water_supply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('water_supply_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'water_supply',
                'managed': False,
            },
        ),
    ]
