# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-21 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundariesInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bound_name', models.CharField(max_length=200, verbose_name='Boundary Name')),
                ('bound_code', models.CharField(choices=[('LG', 'Local Government'), ('BOR', 'Board of Revenue'), ('IB', 'Internation Boundaries'), ('AB', 'Administration Boundaries'), ('PID', 'Irrigation Boundaries'), ('IndB', 'Indus Basin Catchments')], max_length=5, verbose_name='Boundary Code')),
                ('bound_level', models.SmallIntegerField(blank=True, null=True, verbose_name='Boundary Level')),
                ('parent_bound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boundaries.BoundariesInfo', verbose_name='Parent Boundaries')),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Info', verbose_name='Table Name')),
            ],
        ),
    ]
