# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-05 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('meeting_management', '0002_auto_20190105_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcalendersync',
            name='sync_by',
            field=models.ForeignKey(blank=True, db_column='sync_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='socialaccount.SocialAccount'),
        ),
    ]
