# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-06 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_management', '0003_tblcalendersync_sync_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcalendersync',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblmeetings',
            options={'managed': True},
        ),
    ]
