# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-06 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_management', '0004_auto_20190106_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmeetings',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='meeting_management.TblUsers'),
        ),
        migrations.AlterField(
            model_name='tblmeetings',
            name='decisions',
            field=models.TextField(),
        ),
    ]
